[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "d54c85b69dff12b656f060358cf0089f2cc38b9e"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "5dd24465ab2be40d78a15e470224db653e4076527705ede906ca5d8512736155"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+1/LibCURL.v8.18.0.x86_64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "5b71e8ac9c6c75f10c4fdef1947dcd1c7ebbb641"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "1f347332593e1a1dd79061227d2c1e84c5d2d4dabfeab8669adb74f9f2316616"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+1/LibCURL.v8.18.0.x86_64-linux-musl.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "c59ca402f106302130213170da3649353234ff5e"
os = "windows"

    [[LibCURL.download]]
    sha256 = "725b09d29fe7b54dd30364aaa5796f964264d72bf38dce9c06965f2b91a24191"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+1/LibCURL.v8.18.0.x86_64-w64-mingw32.tar.gz"
[[LibCURL]]
arch = "i686"
git-tree-sha1 = "e9988532469d0d24c6680d93bfd000eaf5a017ef"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "e8a1821124bb2f1a7b9bebadc4e94896215c5cbcc4b23de0199120558f7e041b"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+1/LibCURL.v8.18.0.i686-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "6ac894da81f44502d3d68a0d4a5418eb042188bf"
libc = "glibc"
os = "linux"

    [[LibCURL.download]]
    sha256 = "6711384ffbf83b3f48ce8f0cd41e217ae1697cdb31af5127cc0ae1901a73c2ed"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+1/LibCURL.v8.18.0.aarch64-linux-gnu.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "6f3d648bf1934f2e556819351faaead5e78970b9"
libc = "musl"
os = "linux"

    [[LibCURL.download]]
    sha256 = "996b9adf4eb346480e48be9b58a5ed82a795fd9a7657459cbda20124949e2f52"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+1/LibCURL.v8.18.0.aarch64-linux-musl.tar.gz"
[[LibCURL]]
arch = "aarch64"
git-tree-sha1 = "90f659923a878af4094662007d6132c9e6b8a679"
os = "macos"

    [[LibCURL.download]]
    sha256 = "9d0f7721e6f5e743bc9d8082de82e1de75b1fddbdfe97fd171b817ff1d58e3da"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+1/LibCURL.v8.18.0.aarch64-apple-darwin.tar.gz"
[[LibCURL]]
arch = "x86_64"
git-tree-sha1 = "6a56b49f2f799289dac136e494f51a7d86570b4c"
os = "macos"

    [[LibCURL.download]]
    sha256 = "ea7749110f389341c243ec1f44e6777e6e25af6241dabf0bdbb894e08aca561b"
    url = "https://github.com/genotrance/LibCURL_jll.jl/releases/download/LibCURL-v8.18.0+1/LibCURL.v8.18.0.x86_64-apple-darwin.tar.gz"
